version: '3.9'

networks:
  chessnet2:
    driver: localhost
    ipam:
      config:
        - subnet: 172.17.0.0/16

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      chessnet2:
        ipv4_address: 172.17.0.2
    ports:
      - "5672:5672"
      - "15672:15672"

  handler:
    build: ./handler
    networks:
      chessnet2:
        ipv4_address: 172.17.0.3
    ports:
      - "4443:4443"

  chess_server:
    build: ./chess_server
    networks:
      chessnet2:
        ipv4_address: 172.17.0.4
    ports:
      - "5000:5000"
