// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/chess.proto

package chesspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChessService_FindGame_FullMethodName = "/chess.ChessService/FindGame"
	ChessService_Move_FullMethodName     = "/chess.ChessService/Move"
	ChessService_Forfeit_FullMethodName  = "/chess.ChessService/Forfeit"
)

// ChessServiceClient is the client API for ChessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChessServiceClient interface {
	FindGame(ctx context.Context, in *FindGameRequest, opts ...grpc.CallOption) (*FindGameResponse, error)
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
	Forfeit(ctx context.Context, in *ForfeitRequest, opts ...grpc.CallOption) (*ForfeitResponse, error)
}

type chessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChessServiceClient(cc grpc.ClientConnInterface) ChessServiceClient {
	return &chessServiceClient{cc}
}

func (c *chessServiceClient) FindGame(ctx context.Context, in *FindGameRequest, opts ...grpc.CallOption) (*FindGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindGameResponse)
	err := c.cc.Invoke(ctx, ChessService_FindGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chessServiceClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, ChessService_Move_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chessServiceClient) Forfeit(ctx context.Context, in *ForfeitRequest, opts ...grpc.CallOption) (*ForfeitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForfeitResponse)
	err := c.cc.Invoke(ctx, ChessService_Forfeit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChessServiceServer is the server API for ChessService service.
// All implementations must embed UnimplementedChessServiceServer
// for forward compatibility.
type ChessServiceServer interface {
	FindGame(context.Context, *FindGameRequest) (*FindGameResponse, error)
	Move(context.Context, *MoveRequest) (*MoveResponse, error)
	Forfeit(context.Context, *ForfeitRequest) (*ForfeitResponse, error)
	mustEmbedUnimplementedChessServiceServer()
}

// UnimplementedChessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChessServiceServer struct{}

func (UnimplementedChessServiceServer) FindGame(context.Context, *FindGameRequest) (*FindGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindGame not implemented")
}
func (UnimplementedChessServiceServer) Move(context.Context, *MoveRequest) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedChessServiceServer) Forfeit(context.Context, *ForfeitRequest) (*ForfeitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forfeit not implemented")
}
func (UnimplementedChessServiceServer) mustEmbedUnimplementedChessServiceServer() {}
func (UnimplementedChessServiceServer) testEmbeddedByValue()                      {}

// UnsafeChessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChessServiceServer will
// result in compilation errors.
type UnsafeChessServiceServer interface {
	mustEmbedUnimplementedChessServiceServer()
}

func RegisterChessServiceServer(s grpc.ServiceRegistrar, srv ChessServiceServer) {
	// If the following call pancis, it indicates UnimplementedChessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChessService_ServiceDesc, srv)
}

func _ChessService_FindGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessServiceServer).FindGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessService_FindGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessServiceServer).FindGame(ctx, req.(*FindGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChessService_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessServiceServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessService_Move_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessServiceServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChessService_Forfeit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForfeitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessServiceServer).Forfeit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessService_Forfeit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessServiceServer).Forfeit(ctx, req.(*ForfeitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChessService_ServiceDesc is the grpc.ServiceDesc for ChessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chess.ChessService",
	HandlerType: (*ChessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindGame",
			Handler:    _ChessService_FindGame_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _ChessService_Move_Handler,
		},
		{
			MethodName: "Forfeit",
			Handler:    _ChessService_Forfeit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chess.proto",
}

const (
	ClientCallback_BoardUpdate_FullMethodName = "/chess.ClientCallback/BoardUpdate"
)

// ClientCallbackClient is the client API for ClientCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientCallbackClient interface {
	BoardUpdate(ctx context.Context, in *BoardUpdateRequest, opts ...grpc.CallOption) (*BoardUpdateResponse, error)
}

type clientCallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewClientCallbackClient(cc grpc.ClientConnInterface) ClientCallbackClient {
	return &clientCallbackClient{cc}
}

func (c *clientCallbackClient) BoardUpdate(ctx context.Context, in *BoardUpdateRequest, opts ...grpc.CallOption) (*BoardUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardUpdateResponse)
	err := c.cc.Invoke(ctx, ClientCallback_BoardUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientCallbackServer is the server API for ClientCallback service.
// All implementations must embed UnimplementedClientCallbackServer
// for forward compatibility.
type ClientCallbackServer interface {
	BoardUpdate(context.Context, *BoardUpdateRequest) (*BoardUpdateResponse, error)
	mustEmbedUnimplementedClientCallbackServer()
}

// UnimplementedClientCallbackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientCallbackServer struct{}

func (UnimplementedClientCallbackServer) BoardUpdate(context.Context, *BoardUpdateRequest) (*BoardUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BoardUpdate not implemented")
}
func (UnimplementedClientCallbackServer) mustEmbedUnimplementedClientCallbackServer() {}
func (UnimplementedClientCallbackServer) testEmbeddedByValue()                        {}

// UnsafeClientCallbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientCallbackServer will
// result in compilation errors.
type UnsafeClientCallbackServer interface {
	mustEmbedUnimplementedClientCallbackServer()
}

func RegisterClientCallbackServer(s grpc.ServiceRegistrar, srv ClientCallbackServer) {
	// If the following call pancis, it indicates UnimplementedClientCallbackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientCallback_ServiceDesc, srv)
}

func _ClientCallback_BoardUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCallbackServer).BoardUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientCallback_BoardUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCallbackServer).BoardUpdate(ctx, req.(*BoardUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientCallback_ServiceDesc is the grpc.ServiceDesc for ClientCallback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientCallback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chess.ClientCallback",
	HandlerType: (*ClientCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BoardUpdate",
			Handler:    _ClientCallback_BoardUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chess.proto",
}
