# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chess.proto for package 'chess'

require 'grpc'
require 'chess_pb'

module Chess
  module ChessService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chess.ChessService'

      rpc :StartGame, ::Chess::StartGameRequest, ::Chess::StartGameResponse
      rpc :Move, ::Chess::MoveRequest, ::Chess::MoveResponse
      rpc :Forfeit, ::Chess::ForfeitRequest, ::Chess::ForfeitResponse
    end

    Stub = Service.rpc_stub_class
  end
end
