# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chess.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("chess.proto", :syntax => :proto3) do
    add_message "chess.StartGameRequest" do
    end
    add_message "chess.StartGameResponse" do
      optional :game, :string, 1
    end
    add_message "chess.MoveRequest" do
      optional :client_ip, :string, 1
      optional :client_port, :int32, 2
      optional :move, :string, 3
      optional :color, :string, 4
    end
    add_message "chess.MoveResponse" do
      optional :status, :string, 1
      optional :game, :string, 2
    end
    add_message "chess.ForfeitRequest" do
      optional :client_ip, :string, 1
      optional :client_port, :int32, 2
      optional :color, :string, 3
    end
    add_message "chess.ForfeitResponse" do
      optional :status, :string, 1
      optional :message, :string, 2
    end
  end
end

module Chess
  StartGameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chess.StartGameRequest").msgclass
  StartGameResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chess.StartGameResponse").msgclass
  MoveRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chess.MoveRequest").msgclass
  MoveResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chess.MoveResponse").msgclass
  ForfeitRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chess.ForfeitRequest").msgclass
  ForfeitResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chess.ForfeitResponse").msgclass
end
