# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chess.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'chess.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hess.proto\x12\x05\x63hess\"]\n\x0f\x46indGameRequest\x12\x11\n\tclient_ip\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_port\x18\x02 \x01(\x05\x12\x14\n\x0c\x63\x61llback_url\x18\x03 \x01(\t\x12\x0c\n\x04game\x18\x04 \x01(\t\"g\n\x10\x46indGameResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x11\n\tserver_ip\x18\x03 \x01(\t\x12\x13\n\x0bserver_port\x18\x04 \x01(\x05\x12\x0c\n\x04game\x18\x05 \x01(\t\"\x12\n\x10StartGameRequest\"!\n\x11StartGameResponse\x12\x0c\n\x04game\x18\x01 \x01(\t\"R\n\x0bMoveRequest\x12\x11\n\tclient_ip\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_port\x18\x02 \x01(\x05\x12\x0c\n\x04move\x18\x03 \x01(\t\x12\r\n\x05\x63olor\x18\x04 \x01(\t\",\n\x0cMoveResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04game\x18\x02 \x01(\t\"G\n\x0e\x46orfeitRequest\x12\x11\n\tclient_ip\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_port\x18\x02 \x01(\x05\x12\r\n\x05\x63olor\x18\x03 \x01(\t\"2\n\x0f\x46orfeitResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"4\n\x12\x42oardUpdateRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x62oard\x18\x02 \x01(\t\"%\n\x13\x42oardUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xf6\x01\n\x0c\x43hessService\x12;\n\x08\x46indGame\x12\x16.chess.FindGameRequest\x1a\x17.chess.FindGameResponse\x12>\n\tStartGame\x12\x17.chess.StartGameRequest\x1a\x18.chess.StartGameResponse\x12/\n\x04Move\x12\x12.chess.MoveRequest\x1a\x13.chess.MoveResponse\x12\x38\n\x07\x46orfeit\x12\x15.chess.ForfeitRequest\x1a\x16.chess.ForfeitResponse2V\n\x0e\x43lientCallback\x12\x44\n\x0b\x42oardUpdate\x12\x19.chess.BoardUpdateRequest\x1a\x1a.chess.BoardUpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chess_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINDGAMEREQUEST']._serialized_start=22
  _globals['_FINDGAMEREQUEST']._serialized_end=115
  _globals['_FINDGAMERESPONSE']._serialized_start=117
  _globals['_FINDGAMERESPONSE']._serialized_end=220
  _globals['_STARTGAMEREQUEST']._serialized_start=222
  _globals['_STARTGAMEREQUEST']._serialized_end=240
  _globals['_STARTGAMERESPONSE']._serialized_start=242
  _globals['_STARTGAMERESPONSE']._serialized_end=275
  _globals['_MOVEREQUEST']._serialized_start=277
  _globals['_MOVEREQUEST']._serialized_end=359
  _globals['_MOVERESPONSE']._serialized_start=361
  _globals['_MOVERESPONSE']._serialized_end=405
  _globals['_FORFEITREQUEST']._serialized_start=407
  _globals['_FORFEITREQUEST']._serialized_end=478
  _globals['_FORFEITRESPONSE']._serialized_start=480
  _globals['_FORFEITRESPONSE']._serialized_end=530
  _globals['_BOARDUPDATEREQUEST']._serialized_start=532
  _globals['_BOARDUPDATEREQUEST']._serialized_end=584
  _globals['_BOARDUPDATERESPONSE']._serialized_start=586
  _globals['_BOARDUPDATERESPONSE']._serialized_end=623
  _globals['_CHESSSERVICE']._serialized_start=626
  _globals['_CHESSSERVICE']._serialized_end=872
  _globals['_CLIENTCALLBACK']._serialized_start=874
  _globals['_CLIENTCALLBACK']._serialized_end=960
# @@protoc_insertion_point(module_scope)
